#!/usr/bin/env python3
"""Configuration file for the Sphinx documentation builder."""

import datetime
import os
import re
import sys
from pathlib import Path

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

ON_READTHEDOCS = os.environ.get("READTHEDOCS") == "True"
if not ON_READTHEDOCS:
    sys.path.insert(0, os.path.abspath("../../src"))

import surfaces  # noqa: E402  # must be after sys.path modification

# -- Extract metadata from pyproject.toml ------------------------------------
# This allows documentation to stay in sync with pyproject.toml automatically


def extract_pyproject_metadata():
    """Extract metadata from pyproject.toml for use in documentation."""
    pyproject_path = Path(__file__).parent.parent.parent / "pyproject.toml"

    metadata = {
        "python_versions": [],
        "min_python": "3.8",
        "dependencies": [],
        "version": surfaces.__version__,
    }

    if pyproject_path.exists():
        content = pyproject_path.read_text()

        # Extract Python versions from classifiers
        # Pattern: "Programming Language :: Python :: 3.XX"
        py_version_pattern = r'"Programming Language :: Python :: (3\.\d+)"'
        versions = re.findall(py_version_pattern, content)
        if versions:
            metadata["python_versions"] = sorted(set(versions))

        # Extract requires-python
        requires_python_match = re.search(r'requires-python\s*=\s*"([^"]+)"', content)
        if requires_python_match:
            req = requires_python_match.group(1)
            # Extract minimum version from ">=3.8" or similar
            min_match = re.search(r">=\s*([\d.]+)", req)
            if min_match:
                metadata["min_python"] = min_match.group(1)

        # Extract core dependencies
        deps_match = re.search(r"dependencies\s*=\s*\[(.*?)\]", content, re.DOTALL)
        if deps_match:
            deps_text = deps_match.group(1)
            # Extract package names (first word before any version specifier)
            dep_names = re.findall(r'"([a-zA-Z][a-zA-Z0-9_-]*)', deps_text)
            metadata["dependencies"] = dep_names

    return metadata


# Extract metadata once at configuration time
PYPROJECT_METADATA = extract_pyproject_metadata()

# Build Python version range string from metadata
_py_versions = PYPROJECT_METADATA["python_versions"]
if _py_versions:
    _py_version_range = f"{_py_versions[0]} - {_py_versions[-1]}"
else:
    _py_version_range = "3.8+"

# -- Project information -----------------------------------------------------
current_year = datetime.datetime.now().year
project = "surfaces"
project_copyright = f"2020 - {current_year} (MIT License)"
author = "Simon Blanke"

# The full version, including alpha/beta/rc tags
CURRENT_VERSION = f"v{surfaces.__version__}"

# If on readthedocs, and we're building the latest version, update tag to generate
# correct links in notebooks
if ON_READTHEDOCS:
    READTHEDOCS_VERSION = os.environ.get("READTHEDOCS_VERSION")
    if READTHEDOCS_VERSION == "latest":
        CURRENT_VERSION = "main"

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.napoleon",  # replaces numpydoc - supports custom sections
    "sphinx.ext.intersphinx",
    "sphinx.ext.linkcode",  # link to GitHub source code via linkcode_resolve()
    "myst_parser",
    "sphinx_copybutton",
    "sphinx_design",
    "sphinx_issues",
    "sphinx.ext.doctest",
    "sphinxcontrib.mermaid",
]

# Recommended by sphinx_design when using the MyST Parser
myst_enable_extensions = ["colon_fence"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# The main toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
    "_build",
    ".ipynb_checkpoints",
    "Thumbs.db",
    ".DS_Store",
]

add_module_names = False

# Hide class name prefix in page TOC (e.g., show "search_space" instead of
# "AckleyFunction.search_space")
toc_object_entries_show_parents = "hide"

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# Napoleon settings (replaces numpydoc)
# https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html
napoleon_google_docstring = False
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True

# Custom sections for engineering and other specialized functions
# These sections appear in docstrings but aren't standard numpydoc sections
napoleon_custom_sections = [
    "Problem Description",
    "Design Variables",
    "Objective Function",
    "Constraints",
    "Search Domain",
    "Global Optimum",
    "Landscape Properties",
]

# generate autosummary even if no references
autosummary_generate = True

# Members and inherited-members default to showing methods and attributes from a
# class or those inherited.
# Member-order orders the documentation in the order of how the members are defined in
# the source code.
autodoc_default_options = {
    "members": True,
    "inherited-members": True,
    "member-order": "bysource",
}

# If true, '()' will be appended to :func: etc. cross-reference text.
add_function_parentheses = False

# Suppress warnings
suppress_warnings = [
    "myst.mathjax",
    "docutils",
    "toc.not_included",
    "autodoc.import_object",
    "autosectionlabel",
    "ref",
]

show_warning_types = True

# Link to GitHub repo for github_issues extension
issues_github_path = "SimonBlanke/Surfaces"


def linkcode_resolve(domain, info):
    """Return URL to source code corresponding.

    Parameters
    ----------
    domain : str
    info : dict

    Returns
    -------
    url : str
    """

    def find_source():
        # try to find the file and line number, based on code from numpy:
        # https://github.com/numpy/numpy/blob/main/doc/source/conf.py#L286
        obj = sys.modules[info["module"]]
        for part in info["fullname"].split("."):
            obj = getattr(obj, part)
        import inspect
        import os

        fn = inspect.getsourcefile(obj)
        fn = os.path.relpath(fn, start=os.path.dirname(surfaces.__file__))
        source, lineno = inspect.getsourcelines(obj)
        return fn, lineno, lineno + len(source) - 1

    if domain != "py" or not info["module"]:
        return None
    try:
        filename = "src/surfaces/%s#L%d-L%d" % find_source()
    except Exception:
        filename = info["module"].replace(".", "/") + ".py"
    return f"https://github.com/SimonBlanke/Surfaces/blob/{CURRENT_VERSION}/{filename}"


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

html_theme = "pydata_sphinx_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.

html_theme_options = {
    "logo": {
        "text": "Surfaces",
    },
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/SimonBlanke/Surfaces",
            "icon": "fab fa-github",
        },
        {
            "name": "Star on GitHub",
            "url": "https://github.com/SimonBlanke/Surfaces/stargazers",
            "icon": "fa-regular fa-star",
        },
    ],
    "show_prev_next": False,
    "use_edit_page_button": False,
    "navbar_start": ["navbar-logo"],
    "navbar_center": ["navbar-nav"],
    "navbar_end": ["theme-switcher", "navbar-icon-links"],
    "show_toc_level": 2,
    "secondary_sidebar_items": ["page-toc", "sourcelink"],
}

html_title = "Surfaces"
html_context = {
    "github_user": "SimonBlanke",
    "github_repo": "Surfaces",
    "github_version": "main",
    "doc_path": "docs/source/",
    "python_version_range": _py_version_range,
}

html_sidebars = {
    "**": ["sidebar-nav-bs.html"],
    "index": [],
    "get_started": [],
    "installation": [],
    "search": [],
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = ["css/custom.css"]
html_js_files = ["js/sidebar-toggle.js"]

html_show_sourcelink = False

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "surfacesdoc"

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    # 'preamble': '',
    # Latex figure (float) alignment
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "surfaces.tex",
        "Surfaces Documentation",
        "Simon Blanke",
        "manual",
    ),
]

# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "surfaces", "Surfaces Documentation", [author], 1)]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "surfaces",
        "Surfaces Documentation",
        author,
        "surfaces",
        "A collection of single-objective black-box optimization functions.",
        "Miscellaneous",
    ),
]


def setup(app):
    """Set up sphinx builder.

    Parameters
    ----------
    app : Sphinx application object
    """

    def adds(pth):
        print("Adding stylesheet: %s" % pth)  # noqa: T201, T001
        app.add_css_file(pth)

    adds("fields.css")  # for parameters, etc.


# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    "python": (f"https://docs.python.org/{sys.version_info.major}", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
    "matplotlib": ("https://matplotlib.org/stable/", None),
    "pandas": ("https://pandas.pydata.org/pandas-docs/stable/", None),
    "scikit-learn": ("https://scikit-learn.org/stable/", None),
}

# -- Options for todo extension ----------------------------------------------
todo_include_todos = False

copybutton_prompt_text = r">>> |\.\.\. |\$ "
copybutton_prompt_is_regexp = True
copybutton_line_continuation_character = "\\"

# -- RST Epilog: Make metadata available as substitutions in RST files -------
# These can be used as |variable_name| in RST files

# Build additional Python versions formatting for RST
if _py_versions:
    _py_versions_inline = ", ".join(_py_versions)
else:
    _py_versions_inline = "3.8+"


# -- Count test functions dynamically ------------------------------------------
# Use the generators module for consistent counting across docs

# Add generators to path
_generators_path = Path(__file__).parent.parent / "_generators"
if str(_generators_path.parent) not in sys.path:
    sys.path.insert(0, str(_generators_path.parent))

try:
    from docs._generators import count_by_category, get_all_test_functions, get_total_count

    _categories = get_all_test_functions()
    _counts = count_by_category(_categories)

    # Algebraic counts
    _n_math_1d = _counts.get("algebraic_1d", 0)
    _n_math_2d = _counts.get("algebraic_2d", 0)
    _n_math_nd = _counts.get("algebraic_nd", 0)
    _n_algebraic = _n_math_1d + _n_math_2d + _n_math_nd

    # ML counts
    _n_ml_classification = _counts.get("ml_tabular_classification", 0)
    _n_ml_regression = _counts.get("ml_tabular_regression", 0)
    _n_ml_image = _counts.get("ml_image_classification", 0)
    _n_ml_ts_clf = _counts.get("ml_timeseries_classification", 0)
    _n_ml_ts_forecast = _counts.get("ml_timeseries_forecasting", 0)
    _n_ml = _n_ml_classification + _n_ml_regression + _n_ml_image + _n_ml_ts_clf + _n_ml_ts_forecast

    # Other counts
    _n_engineering = _counts.get("engineering", 0)
    _n_bbob = _counts.get("bbob", 0)
    _n_cec = _counts.get("cec", 0)

    # Total
    _n_total = get_total_count(_categories)

except ImportError:
    # Fallback if generators not available (e.g., during initial setup)
    _n_math_1d = 1
    _n_math_2d = 18
    _n_math_nd = 5
    _n_algebraic = 24
    _n_ml_classification = 5
    _n_ml_regression = 5
    _n_ml_image = 5
    _n_ml_ts_clf = 3
    _n_ml_ts_forecast = 3
    _n_ml = 21
    _n_engineering = 5
    _n_bbob = 0
    _n_cec = 42
    _n_total = 92

# Backward compatibility aliases
_n_mathematical = _n_algebraic

rst_epilog = f"""
.. |version| replace:: {PYPROJECT_METADATA["version"]}
.. |min_python| replace:: {PYPROJECT_METADATA["min_python"]}
.. |python_versions_list| replace:: {_py_versions_inline}
.. |python_version_range| replace:: {_py_version_range}
.. |current_year| replace:: {current_year}

.. |n_total_functions| replace:: {_n_total}
.. |n_algebraic| replace:: {_n_algebraic}
.. |n_mathematical| replace:: {_n_mathematical}
.. |n_1d| replace:: {_n_math_1d}
.. |n_2d| replace:: {_n_math_2d}
.. |n_nd| replace:: {_n_math_nd}
.. |n_ml| replace:: {_n_ml}
.. |n_ml_classification| replace:: {_n_ml_classification}
.. |n_ml_regression| replace:: {_n_ml_regression}
.. |n_ml_image| replace:: {_n_ml_image}
.. |n_ml_timeseries| replace:: {_n_ml_ts_clf + _n_ml_ts_forecast}
.. |n_engineering| replace:: {_n_engineering}
.. |n_cec| replace:: {_n_cec}
.. |n_bbob| replace:: {_n_bbob}
"""
